# yml文件
version: '3.4'
services:
  mysql-main:
    image: mysql:5.7.22
    restart: always
    #名称(可以为空)
    hostname: mysql-main
    #容器名称
    container_name: mysql-main
    # command: --init-file ./create_db.sql 
    # 修改加密规则
    command: --default-authentication-plugin=mysql_native_password
    ports: 
    - "9306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-conf:/etc/mysql
      - mysql-log:/var/log/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysqldb
    networks:
      - mysql-net
    
  lskypro:
    # build:
    #   # 指定dockerfile文件的所在路径
    #   context: ./lskypro
    #   # 指定Dockerfile文件名称
    #   dockerfile: Dockerfile
    image: zyugat/lskypro:1.6.3
    restart: always
    #名称(可以为空)
    hostname: lskypro
    #容器名称
    container_name: lskypro
    ports: 
      - "9080:80" 
    volumes:
      - lsky-data:/var/www/html
    networks:
      - mysql-net

volumes:
  mysql-data:
    name: mysql-data
    # 不主动创建卷，而从外部寻找
    # external: true
  mysql-conf:
    # external: true
    name: mysql-conf
  mysql-log:
    # external: true
    name: mysql-log
  lsky-data:
    # external: true
    name: lsky-data

networks:
  mysql-net:
    name: mysql-net